
.. index:: instantiation_error/0
.. _methods_instantiation_error_0:

instantiation_error/0
=====================

Description
-----------

::

   instantiation_error

Throws an ``error(instantiation_error, logtalk(Head,Context))``
exception term where ``Head`` is the head of the clause from where this
predicate is called and ``Context`` is the execution context of the
call. This built-in predicate is declared as a private method and thus
cannot be used as a message to an object.

Template and modes
------------------

::

   instantiation_error

Errors
------

``(none)``

Examples
--------

``(none)``

See also
--------

:ref:`methods_catch_3`,
:ref:`methods_throw_1`,
:ref:`methods_context_1`,
:ref:`methods_type_error_2`,
:ref:`methods_domain_error_2`,
:ref:`methods_existence_error_2`,
:ref:`methods_permission_error_3`,
:ref:`methods_representation_error_1`,
:ref:`methods_instantiation_error_0`,
:ref:`methods_resource_error_1`,
:ref:`methods_syntax_error_1`,
:ref:`methods_system_error_0`
